version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marvin123
      POSTGRES_DB: trading_app
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: backend.Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:marvin123@db:5432/trading_app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
